-- ============================================================
-- Production Bootstrap: Create Initial Admin User
-- ============================================================
-- Purpose: Bootstrap script for production deployment
-- Usage: Run ONCE after fresh deployment to create admin user
-- Password: Pass88899 (change immediately after first login!)
-- Argon2id hash for "Pass88899"
-- ============================================================

-- Create admin user (allstar tier - full system access)
INSERT INTO users (uid, email, password_hash, tier, status, organization_id, team_ids, source_product_slug, profile_data, license_status, created_at, updated_at) VALUES
    ('UADMIN0001', 'admin@allowance.test', '$argon2id$v=19$m=19456,t=2,p=1$F20jUfqy4qy4/6z6tOLBhg$Gl8U55p400Q0AXdl2TAWiYGcEWgGs5+4DqvagDNvJrc', 'allstar', 'active', NULL, '[]'::jsonb, 'allowance', '{"first_name": "System", "last_name": "Admin"}', 'valid', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (email) DO UPDATE SET
    tier = 'allstar',
    status = 'active',
    license_status = 'valid',
    updated_at = CURRENT_TIMESTAMP;

-- Create default product (Allowance System)
-- jwt_signing_key is auto-generated by the DB DEFAULT if not provided,
-- but we set a known dev value here for reproducible local testing.
INSERT INTO products (upid, product_slug, name, description, jwt_signing_key) VALUES
    ('UALLOWANCE0001', 'allowance', 'Allowance System', 'Core allowance authorization management system',
     'dev-allowance-jwt-signing-key-for-local-testing-only-do-not-use-in-production')
ON CONFLICT (upid) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description;

-- Create KwongFu product (consumer product — trading platform)
-- jwt_signing_key is set to a known dev value for reproducible local testing.
INSERT INTO products (upid, product_slug, name, description, jwt_signing_key) VALUES
    ('UKWONGFU0001', 'kwongfu', 'KwongFu Trading', 'Headless automated crypto trading platform',
     'dev-kwongfu-jwt-signing-key-for-local-testing-only-do-not-use-in-production')
ON CONFLICT (upid) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description;

-- Create product versions for KwongFu
INSERT INTO product_versions (product_id, version_name, description, features, tier_required, daily_limit, monthly_limit) VALUES
    ((SELECT id FROM products WHERE upid = 'UKWONGFU0001'), 'basic', 'Basic trading features', '{"paper_trading": true, "max_symbols": 1}'::jsonb, 'free'::user_tier, 10, 1000),
    ((SELECT id FROM products WHERE upid = 'UKWONGFU0001'), 'standard', 'Standard trading features', '{"paper_trading": true, "live_trading": true, "max_symbols": 5}'::jsonb, 'standard'::user_tier, 100, 10000),
    ((SELECT id FROM products WHERE upid = 'UKWONGFU0001'), 'premium', 'Premium trading features', '{"paper_trading": true, "live_trading": true, "max_symbols": "unlimited", "backtesting": true}'::jsonb, 'premium'::user_tier, NULL, NULL)
ON CONFLICT (product_id, version_name) DO NOTHING;

-- Create product versions for Allowance
INSERT INTO product_versions (product_id, version_name, description, features, tier_required, daily_limit, monthly_limit) VALUES
    ((SELECT id FROM products WHERE upid = 'UALLOWANCE0001'), 'basic', 'Basic features', '{"max_recipients": 10, "reporting": false}'::jsonb, 'free'::user_tier, 10, 1000),
    ((SELECT id FROM products WHERE upid = 'UALLOWANCE0001'), 'standard', 'Standard features', '{"max_recipients": 100, "reporting": true}'::jsonb, 'standard'::user_tier, 100, 10000),
    ((SELECT id FROM products WHERE upid = 'UALLOWANCE0001'), 'premium', 'Premium features', '{"max_recipients": 1000, "api_access": true}'::jsonb, 'premium'::user_tier, NULL, NULL),
    ((SELECT id FROM products WHERE upid = 'UALLOWANCE0001'), 'allstar', 'AllStar - Full access', '{"max_recipients": "unlimited"}'::jsonb, 'allstar'::user_tier, NULL, NULL)
ON CONFLICT (product_id, version_name) DO NOTHING;

-- ============================================================
-- Verification
-- ============================================================
SELECT 
    '✓ Admin user created' as status,
    email,
    tier,
    status as user_status,
    license_status
FROM users WHERE email = 'admin@allowance.test';

SELECT 
    '✓ Product created' as status,
    upid,
    name
FROM products WHERE upid IN ('UALLOWANCE0001', 'UKWONGFU0001');

-- ============================================================
-- IMPORTANT: Post-deployment steps
-- ============================================================
-- 1. Login with: admin@allowance.test / Pass88899
-- 2. IMMEDIATELY change the password via the UI or API
-- 3. Create organization and additional users as needed
-- ============================================================
